# Generated by Django 6.0.3 on 2026-03-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"verbose_name_plural": "Notes"},
        ),
        migrations.AlterModelOptions(
            name="subtask",
            options={"verbose_name_plural": "SubTasks"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name_plural": "Tasks"},
        ),
        migrations.AlterField(
            model_name="note",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.category",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.priority",
            ),
        ),
    ]
