# Generated by Django 6.0.3 on 2026-03-20 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_note_options_alter_subtask_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={},
        ),
        migrations.AlterModelOptions(
            name="subtask",
            options={},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.RenameField(
            model_name="subtask",
            old_name="task",
            new_name="parent_task",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="priority",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.priority",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
